name: push Actions
on:
  push:
    branches:
      - develop
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du repo
        uses: actions/checkout@v2
      - name: recuperation angular
        uses: bahmutov/npm-install@v1
        #tests
      - run: npm test
      - run: npm run cover

  