name: push Actions
on:
  push:
    branches:
      - develop
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du repo
        uses: actions/checkout@v2
      - name: recuperation angular
        uses: ng-easy/npm-install@v1
        #build et tests
      - run: npm run build
      - run: npm test

  