name: Pull-request workflow
on:
  pull_request:
    branches:
      - main
jobs:
  tests-unitaires:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du repo
        uses: actions/checkout@v
      - name: recuperation de node js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: installation des dépendances
        run: npm i
        #tests
      - run: npm test
      - run: npm run cover
  docker:
    needs: tests-unitaires
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du repo
        uses: actions/checkout@v2
      - name: installation de docker
        uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v1
      - name: connexion a docker
        uses: docker/login-action@v1
        with:
          username: ${{ secret.DOCKER_USERNAME }}
          password: ${{ secret.DOCKER_PASSWORD }}
      - name: construction et push de l'image docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ropi59/weather:latest